spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes in milliseconds
      cache-null-values: false
      key-prefix: true

  redis:
    host: localhost
    port: 6379
    timeout: 60000

  cloud:
    vault:
      uri: http://localhost:8200
      token: root    # Replace with actual token
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: application