apiVersion: apps/v1
kind: Deployment
metadata:
  name: unison-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unison-service
  template:
    metadata:
      labels:
        app: unison-service
    spec:
      containers:
        - name: unison-service
          image: unison:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: unison-service-config
            - secretRef:
                name: unison-vault-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"