apiVersion: v1
kind: Service
metadata:
  name: unison-service
  labels:
    app: unison-service
    tier: backend
spec:
  selector:
    app: unison-service
  type: ClusterIP 
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP
  sessionAffinity: None