apiVersion: v1
kind: Service
metadata:
  name: unison-service
spec:
  selector:
    app: unison-service
  type: NodePort  # <<< CHANGE THIS
  ports:
    - port: 9090         # Internal service port
      targetPort: 9090   # Container port
      nodePort: 30090    # <<< Exposed on localhost:30090
